--------------------------------------------------------
--  파일이 생성됨 - 월요일-2월-18-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence ARTICLE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "REVIEWPROJECT"."ARTICLE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence BNUM_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "REVIEWPROJECT"."BNUM_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence GAME_BNUM_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "REVIEWPROJECT"."GAME_BNUM_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MOVIE_BNUM_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "REVIEWPROJECT"."MOVIE_BNUM_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence REPLY_NUM
--------------------------------------------------------

   CREATE SEQUENCE  "REVIEWPROJECT"."REPLY_NUM"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TV_BNUM_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "REVIEWPROJECT"."TV_BNUM_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ARTICLE
--------------------------------------------------------

  CREATE TABLE "REVIEWPROJECT"."ARTICLE" 
   (	"ID" NUMBER, 
	"TITLE" VARCHAR2(50 BYTE), 
	"CONTENTS" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("CONTENTS") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table BOARD
--------------------------------------------------------

  CREATE TABLE "REVIEWPROJECT"."BOARD" 
   (	"BOARD_NUM" NUMBER, 
	"BOARD_TITLE" VARCHAR2(50 BYTE), 
	"BOARD_CONTENT" CLOB, 
	"BOARD_DATE" DATE, 
	"MEMBER_ID" VARCHAR2(30 BYTE), 
	"LEMON_GRADE" NUMBER, 
	"RECOMMEND" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("BOARD_CONTENT") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table BOARD_GAME
--------------------------------------------------------

  CREATE TABLE "REVIEWPROJECT"."BOARD_GAME" 
   (	"BOARD_NUM" NUMBER, 
	"B_GAME_NUM" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BOARD_MOVIE
--------------------------------------------------------

  CREATE TABLE "REVIEWPROJECT"."BOARD_MOVIE" 
   (	"BOARD_NUM" NUMBER, 
	"B_MOVIE_NUM" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BOARD_TV
--------------------------------------------------------

  CREATE TABLE "REVIEWPROJECT"."BOARD_TV" 
   (	"BOARD_NUM" NUMBER, 
	"B_TV_NUM" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table GRADE
--------------------------------------------------------

  CREATE TABLE "REVIEWPROJECT"."GRADE" 
   (	"BOARD_NUM" NUMBER, 
	"GRADE_NAME1" VARCHAR2(20 BYTE), 
	"GRADE1" NUMBER, 
	"GRADE_NAME2" VARCHAR2(20 BYTE), 
	"GRADE2" NUMBER, 
	"GRADE_NAME3" VARCHAR2(20 BYTE), 
	"GRADE3" NUMBER, 
	"GRADE_NAME4" VARCHAR2(20 BYTE), 
	"GRADE4" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table HASHTAG
--------------------------------------------------------

  CREATE TABLE "REVIEWPROJECT"."HASHTAG" 
   (	"BOARD_NUM" NUMBER, 
	"HASHTAG1" VARCHAR2(50 BYTE), 
	"HASHTAG2" VARCHAR2(50 BYTE), 
	"HASHTAG3" VARCHAR2(50 BYTE), 
	"HASHTAG4" VARCHAR2(50 BYTE), 
	"HASHTAG5" VARCHAR2(50 BYTE), 
	"HASHTAG6" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LIKEIT
--------------------------------------------------------

  CREATE TABLE "REVIEWPROJECT"."LIKEIT" 
   (	"BOARD_NUM" NUMBER, 
	"MEMBER_ID" VARCHAR2(30 BYTE), 
	"LIKEIT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "REVIEWPROJECT"."MEMBER" 
   (	"MEMBER_ID" VARCHAR2(30 BYTE), 
	"MEMBER_PW" VARCHAR2(30 BYTE), 
	"MEMBER_NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REPLY
--------------------------------------------------------

  CREATE TABLE "REVIEWPROJECT"."REPLY" 
   (	"REPLY_NUM" NUMBER, 
	"BOARD_NUM" NUMBER, 
	"MEMBER_ID" VARCHAR2(30 BYTE), 
	"REPLY_CONTENT" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into REVIEWPROJECT.ARTICLE
SET DEFINE OFF;
Insert into REVIEWPROJECT.ARTICLE (ID,TITLE) values (28,'텍스트 컬러 테스트');
Insert into REVIEWPROJECT.ARTICLE (ID,TITLE) values (42,'ss');
Insert into REVIEWPROJECT.ARTICLE (ID,TITLE) values (2,'hello');
Insert into REVIEWPROJECT.ARTICLE (ID,TITLE) values (3,'test2');
Insert into REVIEWPROJECT.ARTICLE (ID,TITLE) values (4,'테스트3');
Insert into REVIEWPROJECT.ARTICLE (ID,TITLE) values (21,'에디터 테스트');
Insert into REVIEWPROJECT.ARTICLE (ID,TITLE) values (22,'d');
Insert into REVIEWPROJECT.ARTICLE (ID,TITLE) values (23,'에디터-wysiwyg 타입');
Insert into REVIEWPROJECT.ARTICLE (ID,TITLE) values (24,'사진 테스트');
Insert into REVIEWPROJECT.ARTICLE (ID,TITLE) values (25,'사진 테스트2');
Insert into REVIEWPROJECT.ARTICLE (ID,TITLE) values (26,'사진 테스트3');
Insert into REVIEWPROJECT.ARTICLE (ID,TITLE) values (29,'테스트');
Insert into REVIEWPROJECT.ARTICLE (ID,TITLE) values (41,'aaa');
Insert into REVIEWPROJECT.ARTICLE (ID,TITLE) values (43,'weee');
Insert into REVIEWPROJECT.ARTICLE (ID,TITLE) values (27,'링크 테스트');
REM INSERTING into REVIEWPROJECT.BOARD
SET DEFINE OFF;
REM INSERTING into REVIEWPROJECT.BOARD_GAME
SET DEFINE OFF;
REM INSERTING into REVIEWPROJECT.BOARD_MOVIE
SET DEFINE OFF;
REM INSERTING into REVIEWPROJECT.BOARD_TV
SET DEFINE OFF;
REM INSERTING into REVIEWPROJECT.GRADE
SET DEFINE OFF;
REM INSERTING into REVIEWPROJECT.HASHTAG
SET DEFINE OFF;
REM INSERTING into REVIEWPROJECT.LIKEIT
SET DEFINE OFF;
REM INSERTING into REVIEWPROJECT.MEMBER
SET DEFINE OFF;
REM INSERTING into REVIEWPROJECT.REPLY
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index BOARD_GAME_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "REVIEWPROJECT"."BOARD_GAME_PK" ON "REVIEWPROJECT"."BOARD_GAME" ("B_GAME_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index REPLY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "REVIEWPROJECT"."REPLY_PK" ON "REVIEWPROJECT"."REPLY" ("REPLY_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MEMBER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "REVIEWPROJECT"."MEMBER_PK" ON "REVIEWPROJECT"."MEMBER" ("MEMBER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index BOARD_MOVIE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "REVIEWPROJECT"."BOARD_MOVIE_PK" ON "REVIEWPROJECT"."BOARD_MOVIE" ("B_MOVIE_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ARTICLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "REVIEWPROJECT"."ARTICLE_PK" ON "REVIEWPROJECT"."ARTICLE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index BOARD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "REVIEWPROJECT"."BOARD_PK" ON "REVIEWPROJECT"."BOARD" ("BOARD_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index BOARD_TV_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "REVIEWPROJECT"."BOARD_TV_PK" ON "REVIEWPROJECT"."BOARD_TV" ("B_TV_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table REPLY
--------------------------------------------------------

  ALTER TABLE "REVIEWPROJECT"."REPLY" MODIFY ("REPLY_NUM" NOT NULL ENABLE);
  ALTER TABLE "REVIEWPROJECT"."REPLY" ADD CONSTRAINT "REPLY_PK" PRIMARY KEY ("REPLY_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BOARD_TV
--------------------------------------------------------

  ALTER TABLE "REVIEWPROJECT"."BOARD_TV" ADD CONSTRAINT "BOARD_TV_PK" PRIMARY KEY ("B_TV_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "REVIEWPROJECT"."BOARD_TV" MODIFY ("B_TV_NUM" NOT NULL ENABLE);
  ALTER TABLE "REVIEWPROJECT"."BOARD_TV" MODIFY ("BOARD_NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GRADE
--------------------------------------------------------

  ALTER TABLE "REVIEWPROJECT"."GRADE" MODIFY ("GRADE_NAME1" NOT NULL ENABLE);
  ALTER TABLE "REVIEWPROJECT"."GRADE" MODIFY ("BOARD_NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LIKEIT
--------------------------------------------------------

  ALTER TABLE "REVIEWPROJECT"."LIKEIT" MODIFY ("BOARD_NUM" NOT NULL ENABLE);
  ALTER TABLE "REVIEWPROJECT"."LIKEIT" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BOARD
--------------------------------------------------------

  ALTER TABLE "REVIEWPROJECT"."BOARD" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "REVIEWPROJECT"."BOARD" MODIFY ("BOARD_DATE" NOT NULL ENABLE);
  ALTER TABLE "REVIEWPROJECT"."BOARD" MODIFY ("BOARD_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "REVIEWPROJECT"."BOARD" MODIFY ("BOARD_TITLE" NOT NULL ENABLE);
  ALTER TABLE "REVIEWPROJECT"."BOARD" MODIFY ("BOARD_NUM" NOT NULL ENABLE);
  ALTER TABLE "REVIEWPROJECT"."BOARD" ADD CONSTRAINT "BOARD_PK" PRIMARY KEY ("BOARD_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ARTICLE
--------------------------------------------------------

  ALTER TABLE "REVIEWPROJECT"."ARTICLE" ADD CONSTRAINT "ARTICLE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "REVIEWPROJECT"."ARTICLE" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "REVIEWPROJECT"."ARTICLE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BOARD_MOVIE
--------------------------------------------------------

  ALTER TABLE "REVIEWPROJECT"."BOARD_MOVIE" ADD CONSTRAINT "BOARD_MOVIE_PK" PRIMARY KEY ("B_MOVIE_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "REVIEWPROJECT"."BOARD_MOVIE" MODIFY ("BOARD_NUM" NOT NULL ENABLE);
  ALTER TABLE "REVIEWPROJECT"."BOARD_MOVIE" MODIFY ("B_MOVIE_NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HASHTAG
--------------------------------------------------------

  ALTER TABLE "REVIEWPROJECT"."HASHTAG" MODIFY ("BOARD_NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BOARD_GAME
--------------------------------------------------------

  ALTER TABLE "REVIEWPROJECT"."BOARD_GAME" MODIFY ("BOARD_NUM" NOT NULL ENABLE);
  ALTER TABLE "REVIEWPROJECT"."BOARD_GAME" MODIFY ("B_GAME_NUM" NOT NULL ENABLE);
  ALTER TABLE "REVIEWPROJECT"."BOARD_GAME" ADD CONSTRAINT "BOARD_GAME_PK" PRIMARY KEY ("B_GAME_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "REVIEWPROJECT"."MEMBER" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "REVIEWPROJECT"."MEMBER" ADD CONSTRAINT "MEMBER_PK" PRIMARY KEY ("MEMBER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "REVIEWPROJECT"."MEMBER" MODIFY ("MEMBER_PW" NOT NULL ENABLE);
  ALTER TABLE "REVIEWPROJECT"."MEMBER" MODIFY ("MEMBER_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BOARD
--------------------------------------------------------

  ALTER TABLE "REVIEWPROJECT"."BOARD" ADD CONSTRAINT "BOARD_FK1" FOREIGN KEY ("MEMBER_ID")
	  REFERENCES "REVIEWPROJECT"."MEMBER" ("MEMBER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BOARD_GAME
--------------------------------------------------------

  ALTER TABLE "REVIEWPROJECT"."BOARD_GAME" ADD CONSTRAINT "BOARD_GAME_FK1" FOREIGN KEY ("BOARD_NUM")
	  REFERENCES "REVIEWPROJECT"."BOARD" ("BOARD_NUM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BOARD_MOVIE
--------------------------------------------------------

  ALTER TABLE "REVIEWPROJECT"."BOARD_MOVIE" ADD CONSTRAINT "BOARD_MOVIE_FK1" FOREIGN KEY ("BOARD_NUM")
	  REFERENCES "REVIEWPROJECT"."BOARD" ("BOARD_NUM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BOARD_TV
--------------------------------------------------------

  ALTER TABLE "REVIEWPROJECT"."BOARD_TV" ADD CONSTRAINT "BOARD_TV_FK1" FOREIGN KEY ("BOARD_NUM")
	  REFERENCES "REVIEWPROJECT"."BOARD" ("BOARD_NUM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HASHTAG
--------------------------------------------------------

  ALTER TABLE "REVIEWPROJECT"."HASHTAG" ADD CONSTRAINT "HASHTAG_FK1" FOREIGN KEY ("BOARD_NUM")
	  REFERENCES "REVIEWPROJECT"."BOARD" ("BOARD_NUM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LIKEIT
--------------------------------------------------------

  ALTER TABLE "REVIEWPROJECT"."LIKEIT" ADD CONSTRAINT "LIKEIT_FK1" FOREIGN KEY ("BOARD_NUM")
	  REFERENCES "REVIEWPROJECT"."BOARD" ("BOARD_NUM") ENABLE;
  ALTER TABLE "REVIEWPROJECT"."LIKEIT" ADD CONSTRAINT "LIKEIT_FK2" FOREIGN KEY ("MEMBER_ID")
	  REFERENCES "REVIEWPROJECT"."MEMBER" ("MEMBER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REPLY
--------------------------------------------------------

  ALTER TABLE "REVIEWPROJECT"."REPLY" ADD CONSTRAINT "REPLY_FK1" FOREIGN KEY ("BOARD_NUM")
	  REFERENCES "REVIEWPROJECT"."BOARD" ("BOARD_NUM") ENABLE;
  ALTER TABLE "REVIEWPROJECT"."REPLY" ADD CONSTRAINT "REPLY_FK2" FOREIGN KEY ("MEMBER_ID")
	  REFERENCES "REVIEWPROJECT"."MEMBER" ("MEMBER_ID") ENABLE;
